/* eslint-disable @next/next/no-img-element */
import Image from "next/image";
import React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import Head from "next/head";

const Project = () => {
  const router = useRouter();
  return (
    <div className="w-full">
      <Head>
        <title>Johan Leon | Personal project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="w-screen h-[50vh] relative">
        <div className="absolute top-0 left-0 w-full h-[50vh] bg-black/70 z-10" />
        <Image
          className="absolute z-1 w-full h-full object-cover"
          src={router.query.backgroundImg}
          alt={router.query.title}
          layout="fill"
        />
        <div className="absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2">
          <h2 className="py-2">{router.query.title}</h2>
        </div>
      </div>

      <div className="max-w-[1240px] mx-auto p-2 grid md:grid-cols-5 gap-8 py-8">
        <div className="col-span-4">
          <p>Project</p>
          <h2>Overview</h2>
          <p>{router.query.overview}</p>
          {router.query.deploy ? (
            <a href={router.query.projectURL} target="_blank" rel="noreferrer">
              <button className="px-8 py-2 mt-4 mr-8">Demo</button>
            </a>
          ) : (
            <a href={router.query.projectURL} target="_blank" rel="noreferrer">
              <button className="px-8 py-2 mt-4 mr-8">Code</button>
            </a>
          )}
        </div>
        <div className="col-span-4 md:col-span-1 shadow-xl shadow-gray-400 rounded-xl py-4">
          <div className="p-2">
            <p className="text-center font-bold pb-2">Technologies</p>
            <p className="text-gray-600 py-2 flex items-center text-center p-4">
              {router.query.tecnologys}
            </p>
          </div>
        </div>
        <Link href="/#projects">
          <p className="underline cursor-pointer">Back</p>
        </Link>
      </div>
    </div>
  );
};

export default Project;
